# Python Assignment

In [1]:
import numpy as np
import pandas as pd

## Solution 1

In [3]:
lst = []

lst = [int(x) for x in input("Enter multiple value: ").split()] 
print(lst)

myarr = np.asarray(lst)
myarr.reshape(2,4)

Enter multiple value: 1 2 3 4 5 6 7 8
[1, 2, 3, 4, 5, 6, 7, 8]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## Solution 2

In [4]:
lst = []

lst = [int(x) for x in input("Enter multiple value: ").split()]

myarr = np.asarray(lst)

float_arr = myarr.astype(np.float)

print("Float converted array", float_arr)

reverse_a = float_arr[::-1]

print("Reverse of float converted array", reverse_a)

Enter multiple value: 1 2 2 4
Float converted array [ 1.  2.  2.  4.]
Reverse of float converted array [ 4.  2.  2.  1.]


## Solution 3

In [8]:
x, y = input().split()
i = int(x)
j = int(y)

inp = input().split()
for a in range(i):
    for b in range(j):
        arr[a][b]=inp[a*j+b]
    
print("Original Array")
print(arr)

print("\nTransoposed Array")
print(arr.transpose())

print("\nFlattened Array")
print(arr.flatten())

2 2
1 3 5 6
Original Array
[[ 1.  3.]
 [ 5.  6.]]

Transoposed Array
[[ 1.  5.]
 [ 3.  6.]]

Flattened Array
[ 1.  3.  5.  6.]


## Solution 4

In [11]:
x,y,z = input().split()

a = int(x)
b = int(y)
c = int(z)

temp_arr1 = np.zeros((a,c))
temp_arr2 = np.zeros((b,c))

for i in range(0,a):
    inp = input().split()
    for j in range(0,c):
        temp_arr1[i][j] = inp[j]

i2 = b

for i2 in range(0,b):
    inp2 = input().split()
    for j2 in range(c):
        temp_arr2[i2][j2] = inp2[j2]
        
concat_arr = np.concatenate((temp_arr1, temp_arr2))
print("Concatenated Array")
print (concat_arr)

2 2 2
1 2
1 2
1 5
3 5
Concatenated Array
[[ 1.  2.]
 [ 1.  2.]
 [ 1.  5.]
 [ 3.  5.]]


# Solution 5

In [14]:
x, y, z = input().split()

i = int(x)
j = int(y)
k = int(z)

arr1 = np.zeros((j,k), dtype = np.int)
arr2 = np.ones((j,k), dtype = np.int)

print("Zero Array")
for a in range (i):
    print(arr1)
    
print("\nOnes Array")
for a in range (i):
    print(arr2)

4 2 2
Zero Array
[[0 0]
 [0 0]]
[[0 0]
 [0 0]]
[[0 0]
 [0 0]]
[[0 0]
 [0 0]]

Ones Array
[[1 1]
 [1 1]]
[[1 1]
 [1 1]]
[[1 1]
 [1 1]]
[[1 1]
 [1 1]]


## Solution 6

In [15]:
x, y = input().split()

i = int(x)
j = int(y)

arr1 = np.zeros((i,j), dtype = np.int)
arr2 = np.zeros((i,j), dtype = np.int)

for a in range(0,i):
    inp = input().split()
    for b in range(0,j):
        arr1[a][b] = inp[b]
        

for a in range(0,i):
    inp = input().split()
    for b in range(0,j):
        arr2[a][b] = inp[b]

print("\n")
print("Array Sum \n", arr1+arr2)

print("\n")
print("Array Subtraction\n", arr1-arr2)

print("\n")
print("Array Multiplication\n", arr1*arr2)

print("\n")
print("Array Division\n", arr1/arr2)

print("\n")
print("Array Mod\n",arr1%arr2)

print("\n")
print("Array Power\n",arr1**arr2)

2 2
1 2
3 4
2 4
4 5


Array Sum 
 [[3 6]
 [7 9]]


Array Subtraction
 [[-1 -2]
 [-1 -1]]


Array Multiplication
 [[ 2  8]
 [12 20]]


Array Division
 [[ 0.5   0.5 ]
 [ 0.75  0.8 ]]


Array Mod
 [[1 2]
 [3 4]]


Array Power
 [[   1   16]
 [  81 1024]]


## Solution 7 - Floor, Ceiling & Rint

In [17]:
list = input().split()

arr=[float(e) for e in list]

print ("Floor of array ", np.floor(arr))

print ("\nCeiling of array ", np.ceil(arr))

print ("\nRint of array ", np.rint(arr))

1.2 3.5 6.7 4.2 9.8 3.3
Floor of array  [ 1.  3.  6.  4.  9.  3.]

Ceiling of array  [  2.   4.   7.   5.  10.   4.]

Rint of array  [  1.   4.   7.   4.  10.   3.]


## Solution 8 - Sum & Prod Function

In [20]:
x, y = input().split()

a = int(x)
b = int(y)

arr1 = np.zeros((a,b))

for i in range(0,a):
    inp = input().split()
    for j in range(0,b):
        arr1[i][j] = inp[j]

temp_arr1 = np.sum(arr1, axis = 0)

print("\nSum of array elements")
print(temp_arr1)

print("\nProduct of array elements")
print(np.prod(temp_arr1))

2 3
1 2 4
2 4 6

Sum of array elements
[  3.   6.  10.]

Product of array elements
180.0


## Solution 9 - Min and Max

In [21]:
x, y = input().split()

a = int(x)
b = int(y)

arr1 = np.zeros((a,b))

for i in range(0,a):
    inp = input().split()
    for j in range(0,b):
        arr1[i][j] = inp[j]
        

temp_arr = np.min(arr1,axis = 0)
print("\nMax along axis = 0")
print(np.max(arr1))

temp_arr = np.min(arr1,axis = 1)
print("\nMax along axis = 1")
print(np.max(arr1))

2 3
1 2 3
3 4 5

Max along axis = 0
5.0

Max along axis = 1
5.0


## Solution 10 - Mean, Standard Deviation and Variance

In [22]:
x, y = input().split()

a = int(x)
b = int(y)

arr1 = np.zeros((a,b))

for i in range(0,a):
    inp = input().split()
    for j in range(0,b):
        arr1[i][j] = inp[j]
        
print("\nMean of Array")
print(np.mean(arr1,axis=0))
print(np.mean(arr1,axis=1))

print("\nVariance of Array")
print(np.var(arr1,axis=0))
print(np.var(arr1,axis=1))

print("\nStandard deviation of Array")
print(np.std(arr1,axis=0))
print(np.std(arr1,axis=1))

2 3
1 3 5
3 4 6

Mean of Array
[ 2.   3.5  5.5]
[ 3.          4.33333333]

Variance of Array
[ 1.    0.25  0.25]
[ 2.66666667  1.55555556]

Standard deviation of Array
[ 1.   0.5  0.5]
[ 1.63299316  1.24721913]
